---
# This configuration file is documented in docs/02-configuration.md.
# You can get all default values with `akvorado orchestrator /dev/null
# --dump --check` or `docker compose run akvorado-orchestrator
# orchestrator /dev/null --dump --check`.

kafka:
  topic: flows
  version: 3.3.1
  brokers:
    - kafka:9092
  topic-configuration:
    num-partitions: 8
    replication-factor: 1
    config-entries:
      # The retention policy in Kafka is mainly here to keep a buffer
      # for ClickHouse.
      segment.bytes: 1073741824
      retention.ms: 86400000 # 1 day
      cleanup.policy: delete
      compression.type: producer

geoip:
  optional: true
  # When running on Docker, these paths are inside the container. By default,
  # IPinfo databases are used. (https://ipinfo.io/)
  asn-database:
    - /usr/share/GeoIP/asn.mmdb
  geo-database:
    - /usr/share/GeoIP/country.mmdb
  # If you want to use MaxmindDB, check `.env`, `docker-compose-maxmind.yml` and
  # update these paths:
  #asn-database:
  # - /usr/share/GeoIP/GeoLite2-ASN.mmdb
  #geo-database:
  # - /usr/share/GeoIP/GeoLite2-Country.mmdb

clickhouse:
  orchestrator-url: http://akvorado-orchestrator:8080
  kafka:
    consumers: 4
  servers:
    - clickhouse:9000
  prometheus-endpoint: /metrics
  asns:
    15557: SFR
  networks:
    # You should customize this section with your networks. This
    # populates the Src/DstNetName/Role/Site/Region/Tenant fields.
    10.0.0.0/24:
      name: Default
      role: default
    10.0.12.0/24:
      name: Focus
      role: focus
    10.0.251.0/24:
      name: Focus IOT
      role: focus iot
    10.250.0.0/16:
      name: Guest
      role: guest
    10.0.14.0/24:
      name: S03 -
      role: s03
    10.0.2.0/24:
      name: S07 Human Elite
      role: s07 human elite
    10.0.3.0/24:
      name: N03 Financeal
      role: n03 financeal
    10.0.4.0/24:
      name: N06 ZTHT
      role: n06 zhtht
    10.0.6.0/24:
      name: S01 - Gaminho
      role: s01 gaminho
    10.0.8.0/24:
      name: N05 - Epalia
      role: n05 epalia
    10.0.10.0/24:
      name: S04 Unisoap
      role: s04 unisoap
    10.0.7.0/24:
      name: S05 Ipokrat
      role: s05 ipokrat
    10.0.9.0/24:
      name: S06 Athribis
      role: s06 athribis
    10.0.13.0/24:
      name: N02
      role: n02
    10.0.16.0/24:
      name: N06 Bis - Samia M...
      role: n06 bis samia m
    10.0.20.0/24:
      name: N06 Digit Only
      role: n06 digit only
    10.0.28.0/24:
      name: N04-5 Huggy R...
      role: n04-5 huggy r
    10.0.29.0/24:
      name: S06 Silyane
      role: s06 silyane
  network-sources: []
    # amazon:
    #   url: https://ip-ranges.amazonaws.com/ip-ranges.json
    #   interval: 6h
    #   transform: |
    #     (.prefixes + .ipv6_prefixes)[] |
    #     { prefix: (.ip_prefix // .ipv6_prefix), tenant: "amazon", region: .region, role: .service|ascii_downcase }
    # gcp:
    #   url: https://www.gstatic.com/ipranges/cloud.json
    #   interval: 6h
    #   transform: |
    #     .prefixes[] |
    #     { prefix: (.ipv4Prefix // .ipv6Prefix), tenant: "google-cloud", region: .scope }

inlet: !include "inlet.yaml"
console: !include "console.yaml"

# Remove the following line if you don't want to get demo data
# demo-exporter: !include "demo.yaml"
